---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - make all
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: "iHPMtQUbJJOEVMqm7ekTpK7VeL40RUKrOXLYKGqygY9gNbuoRkZpvYI5AVHXRmphEq9vgm9tmKDfVSIaz9XCADBGaNDXLbiw+cxZxdA2HeI18s15BXIJqX7i6bAXCELEZJGwrMOw8bjCewaSZHXDOrXx07b6DlIkpUKHUMgONdU5qhLTWyO0frgGofrF4PNrA1fz3sRHf50+iWrYtKX+cFqvjBQMj6xKDWFmMT5gIrUTmYwRZYTFQCpdCAaR4kd49BoseOFk37MJOU2gjpGP6V1RauvrMkTW4LJP/X+RM29U3hFcdanWVXubpa/JFwv0IcPLxr1gd6kVNGqE/66ehJeLKz7++1H4qGOg13JUfCjgPk7BQSTcpIVuaIEhGvyj1ddiTvdeYq5eTwp2nMc4SiDHRJ2gw9n7x9eyvJRDoXQQPP0HyiRbUD4mX4TNIr9Q7ahyUUr0oGDUjcZVms1WuK8CxlnMHNYNedTQLytr8wtTQEw4YQfgwKg/Qs4wdx41R1qzj70BkDUhE8Pria8v5sI53FonUyLt/M62AzHipeaiAQ7dzli8gZP2u5R75yPE/x51R5877mtuhOn5ZfnfxCesQxL5OHxJDv/F/vDRIiRHkHWG8sOx1AjJnPxCHKSciZrKsVfPTn6s0bcwhhhyCdNOe/8wlenMcUW7wBBso1A="
    file:
      - cross/tdash-linux-amd64.md5
      - cross/tdash-windows-386.sha256
      - cross/tdash-linux-arm
      - cross/tdash-darwin-amd64.md5
      - cross/tdash-darwin-amd64
      - cross/tdash-linux-arm64.sha256
      - cross/tdash-linux-arm.sha256
      - cross/tdash-linux-386.sha256
      - cross/tdash-darwin-386.md5
      - cross/tdash-windows-386.md5
      - cross/tdash-freebsd-amd64.md5
      - cross/tdash-linux-arm64.md5
      - cross/tdash-linux-arm64
      - cross/tdash-freebsd-amd64.sha256
      - cross/tdash-freebsd-386.md5
      - cross/tdash-linux-amd64.sha256
      - cross/tdash-linux-386.md5
      - cross/tdash-freebsd-386
      - cross/tdash-windows-amd64
      - cross/tdash-windows-amd64.md5
      - cross/tdash-windows-amd64.sha256
      - cross/tdash-linux-arm.md5
      - cross/tdash-darwin-386.sha256
      - cross/tdash-darwin-amd64.sha256
      - cross/tdash-windows-386
      - cross/tdash-darwin-386
      - cross/tdash-linux-386
      - cross/tdash-freebsd-amd64
      - cross/tdash-freebsd-386.sha256
      - cross/tdash-linux-amd64
    skip_cleanup: true
    on:
      tags: true
